###
GET http://localhost:4200/api HTTP/1.1

###
POST http://localhost:4200/api HTTP/1.1
Content-Type: application/json

{
    "titulo":"El señor de los anillos",
    "autor":"JR Tolkien",
    "editorial":"Eperanza",
    "edicion":21,
    "clasificacion":"Fantasia",
    "estatus":"Prestado"
}

###
GET http://localhost:4200/api/2 HTTP/1.1

###
PUT http://localhost:4200/api/2 HTTP/1.1
Content-Type: application/json

{
    "titulo":"El señor de los anillos",
    "autor":"Sam Thompson",
    "editorial":"Eperanza",
    "edicion":21,
    "clasificacion":"Fantasia",
    "estatus":"Prestado"
}

###
DELETE http://localhost:4200/api/2 HTTP/1.1